default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: platziblog__dev
  username: postgres
  password: mipassword
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: platziblog__test
  username: postgres
  password: mipassword
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: platziblog__prod
  username: postgres
  password: <%= ENV['PLATZIBLOG_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5
